// Code generated by tmp/gen; DO NOT EDIT.
//
// Package term re-exports the public API implemented in internal/, so
// consumers import a single flat "github.com/renatopp/go-term" package.
package term

import internal "github.com/renatopp/go-term/internal"

// Types

type Align = internal.Align

// BorderStyle defines the characters used to draw a Box's border. The zero
// value draws no border at all.
type BorderStyle = internal.BorderStyle

// Box draws an optional border around a single child, with padding between
// the border and the child and margin outside the border.
type Box = internal.Box

// Cell is a single terminal column: its visible content, the number of
// columns it occupies (0 for the placeholder following a wide character, 1
// for a normal character, 2 for a wide one), and the raw SGR sequence
// active when it was written ("" for no styling).
type Cell = internal.Cell

type Color = internal.Color

type Color256 = internal.Color256

type ColorAnsi = internal.ColorAnsi

type ColorMode = internal.ColorMode

type ColorTrue = internal.ColorTrue

type Component = internal.Component

// Confirm renders a message followed by a Yes/No choice, toggled with
// Left/Right/Tab or the y/n keys. The selected option is bracketed so it
// reads even without color, and additionally styled with SelectedStyle. It
// only reacts to key events while Focused.
type Confirm = internal.Confirm

type ContainerItem = internal.ContainerItem

// Cursor renders a single character that can blink on and off, useful for
// marking the insertion point of a text input. Its blink state advances by
// calling Tick, typically forwarded from TickEvent (see Program.WithTick).
type Cursor = internal.Cursor

// CursorPositionEvent reports the terminal's reply to a cursor position
// request (see GetCursorPosition). Row and Col are 1-based.
type CursorPositionEvent = internal.CursorPositionEvent

type Direction = internal.Direction

// Event is a value flowing through the event loop's queue and the package
// bus, carrying events from OS signals, external callbacks, timers, and
// stdin input to be processed by the loop.
type Event = internal.Event

// FloatCounter renders a floating-point value that eases toward a target
// value over time instead of jumping to it immediately. WithValue sets a new
// target and lets it animate there, taking Speed to arrive; Jump sets a
// value immediately with no animation. It does not animate on its own; call
// Tick whenever a new frame should be shown (e.g. from a program-driven
// timer, see Program.WithTick).
type FloatCounter = internal.FloatCounter

// IntCounter renders an integer value that eases toward a target value over
// time instead of jumping to it immediately. WithValue sets a new target and
// lets it animate there, taking Speed to arrive; Jump sets a value
// immediately with no animation. It does not animate on its own; call Tick
// whenever a new frame should be shown (e.g. from a program-driven timer,
// see Program.WithTick).
type IntCounter = internal.IntCounter

type Justify = internal.Justify

// KeyEvent reports a keyboard event read from stdin while in raw mode. Ctrl
// and Alt are always populated when the terminal reports them (Ctrl+letter,
// Alt+key). Shift on a plain or Alt-combined rune is inferred from the
// character's case (e.g. 'A' implies Shift, 'a' doesn't), so it can't be
// told apart from Caps Lock and never applies to Ctrl+letter, whose control
// byte carries no case. Shift on keys with no room for modifiers in plain
// VT100 input otherwise (Enter, Tab, Backspace, Esc, Space, arrows, ...),
// and Ctrl/Alt on those same keys, are only populated when the terminal
// supports the Kitty keyboard protocol or xterm's modifyOtherKeys — see
// EnterRawMode.
type KeyEvent = internal.KeyEvent

// KeyType identifies a key reported by KeyEvent. KeyRune covers ordinary
// character keys (including Ctrl/Alt/Shift combinations, reported via the
// Ctrl, Alt, and Shift fields); the rest name keys with no printable rune of
// their own.
type KeyType = internal.KeyType

type Label = internal.Label

// List renders a vertical list of text items, each prefixed with a bullet.
// Items that don't fit width are wrapped at word boundaries, with wrapped
// lines indented to align under the item's text.
type List = internal.List

type MouseAction = internal.MouseAction

type MouseButton = internal.MouseButton

// MouseEvent reports a mouse event: a button press/release, a drag while a
// button is held, or a wheel scroll. X and Y are 1-based screen columns and
// rows, consistent with CursorPositionEvent.
type MouseEvent = internal.MouseEvent

// MultiEvent groups several events into one, so an Update method can react
// to a single event by producing more than one in return. Use Events to
// build one.
type MultiEvent = internal.MultiEvent

// NumberInput renders a single line of editable numeric text with a
// blinking cursor, scrolling its content horizontally so the cursor always
// stays visible within its width. It only accepts digits, a single leading
// minus sign, and a single decimal point, and only reacts to key events
// while Focused.
type NumberInput = internal.NumberInput

// PasswordInput renders a single line of editable text like TextInput, except
// each entered rune is rendered as MaskChar instead of its actual character,
// so the value stays hidden on screen while still scrolling horizontally so
// the cursor always stays visible within its width. It only reacts to key
// events while Focused.
type PasswordInput = internal.PasswordInput

type Program = internal.Program

// ProgressBar renders a horizontal bar filled in proportion to a value
// between 0 and 1, optionally preceded by a prefix (touching the bar) and
// followed by a suffix (also touching the bar) and a percentage. It does not
// animate on its own; call WithValue whenever progress changes.
type ProgressBar = internal.ProgressBar

type QuitEvent = internal.QuitEvent

type Rect = internal.Rect

type Renderable = internal.Renderable

type ResizeEvent = internal.ResizeEvent

// Select renders a vertical list of options, one highlighted at a time and
// moved with Up/Down. The highlighted option is prefixed with Marker and
// styled with SelectedStyle; the rest are indented to align under it and
// styled with Style. When there are more options than fit height, the list
// scrolls to keep the highlighted option visible. It only reacts to key
// events while Focused.
type Select = internal.Select

// SignalEvent wraps an OS signal delivered to the process.
type SignalEvent = internal.SignalEvent

type Sizeable = internal.Sizeable

// Spinner renders one of a sequence of frames, optionally preceded by a
// prefix and followed by a suffix, advanced by calling Tick. It does not
// animate on its own; call Tick whenever a new frame should be shown (e.g.
// from a program-driven timer). Update, in contrast, paces advancement to
// FrameRate regardless of how often TickEvent fires.
type Spinner = internal.Spinner

// State is an alias for term.State, representing the terminal state for raw
// mode and restoration.
type State = internal.State

type Style = internal.Style

// TextInput renders a single line of editable text with a blinking cursor,
// scrolling its content horizontally so the cursor always stays visible
// within its width. It only reacts to key events while Focused.
type TextInput = internal.TextInput

// TickEvent is sent periodically at the interval configured by
// Program.WithTick (see DefaultTick), letting time-driven components (e.g.
// Spinner) animate. Duration is the actual time elapsed since the previous
// TickEvent, which may drift from the configured interval.
type TickEvent = internal.TickEvent

// Updatable reacts to an event and optionally returns one for further
// processing. A nil return stops that event from being processed any
// further, which lets a component suppress default handling (e.g. the
// program's built-in Ctrl+C behavior) for events it has fully handled
// itself. Returning the event unchanged, a different event, or a MultiEvent
// lets processing continue.
type Updatable = internal.Updatable

// Constants

const AlignAuto = internal.AlignAuto

const AlignCenter = internal.AlignCenter

const AlignEnd = internal.AlignEnd

const AlignStart = internal.AlignStart

const AlignStretch = internal.AlignStretch

const ColorMode256 = internal.ColorMode256

const ColorModeAnsi = internal.ColorModeAnsi

const ColorModeNone = internal.ColorModeNone

const ColorModeTrue = internal.ColorModeTrue

// DefaultBullet is the bullet character used by a List until WithBullet is
// called.
const DefaultBullet = internal.DefaultBullet

// DefaultConfirmNoLabel is the label rendered for the negative option until
// WithNoLabel is called.
const DefaultConfirmNoLabel = internal.DefaultConfirmNoLabel

// DefaultConfirmYesLabel is the label rendered for the affirmative option
// until WithYesLabel is called.
const DefaultConfirmYesLabel = internal.DefaultConfirmYesLabel

// DefaultCursorBlinkSpeed is the interval between blink toggles used by a
// Cursor until WithBlinkSpeed is called.
const DefaultCursorBlinkSpeed = internal.DefaultCursorBlinkSpeed

// DefaultCursorChar is the character used by a Cursor until WithChar is
// called.
const DefaultCursorChar = internal.DefaultCursorChar

// DefaultFPS is used when no FPS is configured via WithFPS.
const DefaultFPS = internal.DefaultFPS

// DefaultFloatCounterSpeed is the time a FloatCounter takes to animate from
// its value at the moment WithValue is called to the new target, used until
// WithSpeed is called.
const DefaultFloatCounterSpeed = internal.DefaultFloatCounterSpeed

// DefaultIntCounterSpeed is the time an IntCounter takes to animate from its
// value at the moment WithValue is called to the new target, used until
// WithSpeed is called.
const DefaultIntCounterSpeed = internal.DefaultIntCounterSpeed

// DefaultNumberInputWidth is used until WithWidth is called. It's large
// enough to be effectively unbounded, so by default the input fills whatever
// width it's rendered with rather than a fixed size.
const DefaultNumberInputWidth = internal.DefaultNumberInputWidth

// DefaultPasswordInputMaskChar is the character rendered in place of each entered
// rune until WithMaskChar is called.
const DefaultPasswordInputMaskChar = internal.DefaultPasswordInputMaskChar

// DefaultPasswordInputWidth is used until WithWidth is called. It's large enough
// to be effectively unbounded, so by default the input fills whatever width
// it's rendered with rather than a fixed size.
const DefaultPasswordInputWidth = internal.DefaultPasswordInputWidth

// DefaultProgressBarEmptyChar is the character used to draw the empty
// portion of a ProgressBar until WithEmptyChar is called.
const DefaultProgressBarEmptyChar = internal.DefaultProgressBarEmptyChar

// DefaultProgressBarFilledChar is the character used to draw the filled
// portion of a ProgressBar until WithFilledChar is called.
const DefaultProgressBarFilledChar = internal.DefaultProgressBarFilledChar

// DefaultProgressBarWidth is used until WithWidth is called. It's large
// enough to be effectively unbounded, so by default the bar's track fills
// whatever width it's rendered with rather than a fixed size.
const DefaultProgressBarWidth = internal.DefaultProgressBarWidth

// DefaultSelectMarker is the text rendered before the highlighted option
// until WithMarker is called.
const DefaultSelectMarker = internal.DefaultSelectMarker

// DefaultSpinnerFrameRate is the interval between frame advances used by a
// Spinner until WithFrameRate is called.
const DefaultSpinnerFrameRate = internal.DefaultSpinnerFrameRate

// DefaultTextInputWidth is used until WithWidth is called. It's large enough
// to be effectively unbounded, so by default the input fills whatever width
// it's rendered with rather than a fixed size.
const DefaultTextInputWidth = internal.DefaultTextInputWidth

// DefaultTick is used when no tick interval is configured via WithTick.
const DefaultTick = internal.DefaultTick

const DirectionColumn = internal.DirectionColumn

const DirectionRow = internal.DirectionRow

const EventCursorPosition = internal.EventCursorPosition

const EventKey = internal.EventKey

const EventMouse = internal.EventMouse

const EventResize = internal.EventResize

const EventSignal = internal.EventSignal

const JustifyCenter = internal.JustifyCenter

const JustifyEnd = internal.JustifyEnd

const JustifySpaceAround = internal.JustifySpaceAround

const JustifySpaceBetween = internal.JustifySpaceBetween

const JustifyStart = internal.JustifyStart

const KeyBackspace = internal.KeyBackspace

const KeyDelete = internal.KeyDelete

const KeyDown = internal.KeyDown

const KeyEnd = internal.KeyEnd

const KeyEnter = internal.KeyEnter

const KeyEsc = internal.KeyEsc

const KeyHome = internal.KeyHome

const KeyInsert = internal.KeyInsert

const KeyLeft = internal.KeyLeft

const KeyPgDown = internal.KeyPgDown

const KeyPgUp = internal.KeyPgUp

const KeyRight = internal.KeyRight

const KeyRune = internal.KeyRune

const KeyTab = internal.KeyTab

const KeyUp = internal.KeyUp

const MouseActionMotion = internal.MouseActionMotion

const MouseActionPress = internal.MouseActionPress

const MouseActionRelease = internal.MouseActionRelease

const MouseButtonLeft = internal.MouseButtonLeft

const MouseButtonMiddle = internal.MouseButtonMiddle

const MouseButtonNone = internal.MouseButtonNone

const MouseButtonRight = internal.MouseButtonRight

const MouseButtonWheelDown = internal.MouseButtonWheelDown

const MouseButtonWheelUp = internal.MouseButtonWheelUp

const Quit = internal.Quit

// Variables

var BorderDouble = internal.BorderDouble

var BorderNone = internal.BorderNone

var BorderRound = internal.BorderRound

var BorderSingle = internal.BorderSingle

var BorderThick = internal.BorderThick

var ColorAmber = internal.ColorAmber

var ColorBlack = internal.ColorBlack

var ColorBlue = internal.ColorBlue

var ColorCyan = internal.ColorCyan

var ColorDarkGray = internal.ColorDarkGray

var ColorEmerald = internal.ColorEmerald

var ColorError = internal.ColorError

var ColorFuchsia = internal.ColorFuchsia

var ColorGray = internal.ColorGray

var ColorGreen = internal.ColorGreen

var ColorIndigo = internal.ColorIndigo

var ColorInfo = internal.ColorInfo

var ColorLightGray = internal.ColorLightGray

var ColorLime = internal.ColorLime

var ColorOrange = internal.ColorOrange

var ColorPink = internal.ColorPink

var ColorPurple = internal.ColorPurple

var ColorRed = internal.ColorRed

var ColorRose = internal.ColorRose

var ColorSky = internal.ColorSky

var ColorSuccess = internal.ColorSuccess

var ColorTeal = internal.ColorTeal

var ColorViolet = internal.ColorViolet

var ColorWarning = internal.ColorWarning

var ColorWhite = internal.ColorWhite

var ColorYellow = internal.ColorYellow

// DefaultFloatCounterFormat is the function used to render a FloatCounter's
// value until WithFormat is called: the value fixed to two decimal places.
var DefaultFloatCounterFormat = internal.DefaultFloatCounterFormat

// DefaultIntCounterFormat is the function used to render an IntCounter's
// value until WithFormat is called: the value as a plain decimal integer.
var DefaultIntCounterFormat = internal.DefaultIntCounterFormat

// DefaultSpinnerFrames are the frames used by a Spinner until WithFrames is
// called: a Braille-based spinner animation.
var DefaultSpinnerFrames = internal.DefaultSpinnerFrames

var Error = internal.Error

var Info = internal.Info

// SpinnerFramesArc cycles through arc segments.
var SpinnerFramesArc = internal.SpinnerFramesArc

// SpinnerFramesArrow cycles through the 8 compass-direction arrows.
var SpinnerFramesArrow = internal.SpinnerFramesArrow

// SpinnerFramesBounceBar bounces a block up and down through its height levels.
var SpinnerFramesBounceBar = internal.SpinnerFramesBounceBar

// SpinnerFramesCircle cycles through quarter-filled circles.
var SpinnerFramesCircle = internal.SpinnerFramesCircle

// SpinnerFramesClock cycles through quarter-turn clock faces.
var SpinnerFramesClock = internal.SpinnerFramesClock

// SpinnerFramesDots2 is an alternate Braille-based spinner animation.
var SpinnerFramesDots2 = internal.SpinnerFramesDots2

// SpinnerFramesDotsOrbit cycles a single Braille dot around its cell.
var SpinnerFramesDotsOrbit = internal.SpinnerFramesDotsOrbit

// SpinnerFramesEarth cycles through the rotating earth emoji.
var SpinnerFramesEarth = internal.SpinnerFramesEarth

// SpinnerFramesEllipsis shows a growing then resetting sequence of dots.
var SpinnerFramesEllipsis = internal.SpinnerFramesEllipsis

// SpinnerFramesLine is a classic ASCII line spinner.
var SpinnerFramesLine = internal.SpinnerFramesLine

// SpinnerFramesMoon cycles through the moon phase emoji.
var SpinnerFramesMoon = internal.SpinnerFramesMoon

// SpinnerFramesQuadrant cycles through single quadrant blocks.
var SpinnerFramesQuadrant = internal.SpinnerFramesQuadrant

// SpinnerFramesSquare cycles through quarter-filled squares.
var SpinnerFramesSquare = internal.SpinnerFramesSquare

// SpinnerFramesSquareToggle toggles between filled and empty squares.
var SpinnerFramesSquareToggle = internal.SpinnerFramesSquareToggle

var Success = internal.Success

var Warning = internal.Warning

// Functions

// BuildRow scans line into exactly width columns, truncating content that
// overflows and padding short lines with blank cells. The line may contain
// SGR escape sequences, which are captured as each cell's Style.
var BuildRow = internal.BuildRow

// ClearLine clears the entire current line and moves the cursor to the
// beginning of the line. It does not move the cursor vertically.
var ClearLine = internal.ClearLine

// ClearLineAfterCursor clears the line from the current cursor position to the
// end of the line, leaving the cursor position unchanged.
var ClearLineAfterCursor = internal.ClearLineAfterCursor

// ClearLineAroundCursor clears the line from the beginning of the line to the
// end of the line, leaving the cursor position unchanged.
var ClearLineAroundCursor = internal.ClearLineAroundCursor

// ClearLineBeforeCursor clears the line from the beginning of the line to the
// current cursor position, leaving the cursor position unchanged.
var ClearLineBeforeCursor = internal.ClearLineBeforeCursor

// ClearScreen clears the entire terminal screen and moves the cursor to the
// top-left corner.
var ClearScreen = internal.ClearScreen

// ClearScreenAroundCursor clears the entire screen after the cursor, leaving
// the cursor position unchanged.
var ClearScreenAfterCursor = internal.ClearScreenAfterCursor

// ClearScreenBeforeCursor clears the entire screen before the cursor, leaving
// the cursor position unchanged.
var ClearScreenBeforeCursor = internal.ClearScreenBeforeCursor

var Column = internal.Column

var Container = internal.Container

// DisableCursorWrap disables line wrapping at the right edge of the terminal.
var DisableCursorWrap = internal.DisableCursorWrap

// DisableMouse turns off mouse reporting enabled by EnableMouse.
var DisableMouse = internal.DisableMouse

// EnableCursorWrap enables line wrapping at the right edge of the terminal.
// When enabled, the cursor moves to the beginning of the next line when it
// reaches the right edge of the terminal. When disabled, the cursor stays at
// the right edge and overwrites existing characters.
var EnableCursorWrap = internal.EnableCursorWrap

// EnableMouse turns on mouse reporting (press, release, drag, and wheel)
// using SGR extended coordinates, which are needed for terminals wider or
// taller than 223 cells.
var EnableMouse = internal.EnableMouse

// EnterAlternateScreen switches the terminal to the alternate screen buffer,
// which is a separate screen that can be used for full-screen applications.
// The original screen is restored when ExitAlternateScreen is called.
var EnterAlternateScreen = internal.EnterAlternateScreen

// EnterRawMode puts stdin into raw mode and starts reading it for mouse,
// keyboard, and other events (see startStdinReader), which are published on
// the package bus. Call ExitRawMode to restore the terminal and stop
// reading.
//
// It also negotiates the richest keyboard-modifier protocol the terminal
// supports (Kitty keyboard protocol, falling back to xterm's
// modifyOtherKeys), so KeyEvent can report Ctrl/Alt/Shift on keys that plain
// VT100 input has no room for, such as Enter, Tab, Backspace, and Esc. This
// adds a short (up to 100ms) delay while probing for Kitty support.
//
// Do not read from stdin while in raw mode, as it will interfere with the
// package's reading and event publishing. Use event callbacks instead.
var EnterRawMode = internal.EnterRawMode

// Events wraps the given events into a MultiEvent for returning from Update.
var Events = internal.Events

// ExitAlternateScreen switches the terminal back to the original screen buffer,
// restoring the screen contents that were present before EnterAlternateScreen
// was called.
var ExitAlternateScreen = internal.ExitAlternateScreen

// ExitRawMode restores the terminal state to what it was before EnterRawMode
// and stops reading stdin for events. It is safe to call even if not in raw mode.
var ExitRawMode = internal.ExitRawMode

// ForceGetCursorPosition queries the terminal for the current cursor position and returns the row and column (1-based), ignoring any errors. If the position
// cannot be determined, it returns zero for both row and column.
var ForceGetCursorPosition = internal.ForceGetCursorPosition

// ForceGetScreenSize returns the current width and height of the terminal in
// columns and rows, ignoring any errors. If the size cannot be determined, it
// returns zero for both width and height.
var ForceGetScreenSize = internal.ForceGetScreenSize

// GetColorLevel returns the current color mode of the terminal, which can be
// None, Basic, 256, or TrueColor. It reflects the terminal's capabilities and
// any overrides set by SetColorLevel.
var GetColorLevel = internal.GetColorLevel

// GetCursorPosition queries the terminal for the current cursor position and
// returns the row and column (1-based). It returns an error if the position
// cannot be determined or if the terminal does not respond in time.
var GetCursorPosition = internal.GetCursorPosition

// GetScreenSize returns the current width and height of the terminal in columns
// and rows. It returns an error if the size cannot be determined.
var GetScreenSize = internal.GetScreenSize

// GetTerminalState returns the current terminal state, which can be used to
// restore the terminal later with RestoreTerminalState.
var GetTerminalState = internal.GetTerminalState

// HideCursor hides the cursor, making it invisible. It does not move the cursor
// or change its position. Call ShowCursor to make the cursor visible again.
var HideCursor = internal.HideCursor

// IsDocker reports whether the program is running inside a Docker container.
var IsDocker = internal.IsDocker

// IsDumb reports whether the terminal is a "dumb" terminal, which has very
// limited capabilities and does not support advanced features like cursor
// movement or color. It is determined by checking the TERM environment variable.
var IsDumb = internal.IsDumb

// IsFile reports whether the given files (or stdin, if noare
// regular files. It returns false for directories, pipes, and terminals.
var IsFile = internal.IsFile

// IsPipe reports whether the given files (or stdin, if none are given) are
// connected to a named pipe (FIFO). It returns false for regular files and
// terminals.
var IsPipe = internal.IsPipe

// IsRaw reports whether stdin is currently in raw mode, which means that input
// is being read directly from the terminal without line buffering or
// processing. It returns true if stdin is in raw mode, false otherwise.
var IsRaw = internal.IsRaw

// IsSSH reports whether the program is running in an SSH session. It checks for
// the presence of SSH-related environment variables.
var IsSSH = internal.IsSSH

// IsTerminal reports whether the given files (or stdin, if none are given)
// are connected to a terminal.
var IsTerminal = internal.IsTerminal

// IsWSL reports whether the program is running inside Windows Subsystem for
// Linux (WSL). It checks for specific environment variables and the presence
// of "microsoft" in /proc/version.
var IsWSL = internal.IsWSL

var Item = internal.Item

// MoveCursorBackward moves the cursor backward (left) by n columns. If n is
// zero, it does nothing.
var MoveCursorBackward = internal.MoveCursorBackward

// MoveCursorDown moves the cursor down by n rows. If n is zero, it does nothing.
var MoveCursorDown = internal.MoveCursorDown

// MoveCursorForward moves the cursor forward (right) by n columns. If n is
// zero, it does nothing.
var MoveCursorForward = internal.MoveCursorForward

// MoveCursorTo moves the cursor to the specified row and column (1-based). If
// either row or col is zero, it does nothing.
var MoveCursorTo = internal.MoveCursorTo

// MoveCursorToBottom moves the cursor to the bottom of the screen (row 9999)
// without changing the column.
var MoveCursorToBottom = internal.MoveCursorToBottom

// MoveCursorToColumn moves the cursor to the specified column (1-based) without
// changing the row. If col is zero, it does nothing.
var MoveCursorToColumn = internal.MoveCursorToColumn

// MoveCursorToEndOfLine moves the cursor to the end of the current line
// (column 9999) without changing the row.
var MoveCursorToEndOfLine = internal.MoveCursorToEndOfLine

// MoveCursorToHome moves the cursor to the top-left corner of the screen
// (row 1, column 1).
var MoveCursorToHome = internal.MoveCursorToHome

// MoveCursorToRow moves the cursor to the specified row (1-based) without
// changing the column. If row is zero, it does nothing.
var MoveCursorToRow = internal.MoveCursorToRow

// MoveCursorToStartOfLine moves the cursor to the beginning of the current line
// (column 1) without changing the row.
var MoveCursorToStartOfLine = internal.MoveCursorToStartOfLine

// MoveCursorUp moves the cursor up by n rows. If n is zero, it does nothing.
var MoveCursorUp = internal.MoveCursorUp

var NewBox = internal.NewBox

var NewColor = internal.NewColor

var NewColor256 = internal.NewColor256

var NewColorAnsi = internal.NewColorAnsi

var NewColorHex = internal.NewColorHex

var NewConfirm = internal.NewConfirm

var NewCursor = internal.NewCursor

var NewFloatCounter = internal.NewFloatCounter

var NewIntCounter = internal.NewIntCounter

var NewLabel = internal.NewLabel

var NewList = internal.NewList

var NewNumberInput = internal.NewNumberInput

var NewPasswordInput = internal.NewPasswordInput

var NewProgram = internal.NewProgram

var NewProgressBar = internal.NewProgressBar

var NewSelect = internal.NewSelect

var NewSpinner = internal.NewSpinner

var NewStyle = internal.NewStyle

var NewTextInput = internal.NewTextInput

// OnEvent invokes fn for every event (key, mouse, resize, cursor position, etc.)
// decoded by the stdin reader started in EnterRawMode. Call the returned stop
// function to stop receiving events. Stdin must be in raw mode (see
// EnterRawMode) for events to be read and published at all.
//
// Some events may come from other sources, such as OS signals or external
// callbacks, so fn may receive events that are not directly related to stdin
// input.
var OnEvent = internal.OnEvent

// OnKey invokes fn for every key event decoded by the stdin reader started in
// EnterRawMode. Call the returned stop function to stop receiving events. Stdin
// must be in raw mode (see EnterRawMode) for events to be read and published at
// all.
var OnKey = internal.OnKey

// OnMouse invokes fn for every mouse event decoded by the stdin reader
// started in EnterRawMode. Call the returned stop function to stop
// receiving events. EnableMouse must be called first, or the terminal won't
// send any events, and stdin must be in raw mode (see EnterRawMode) for
// events to be read and published at all.
var OnMouse = internal.OnMouse

// OnResize polls the screen size and invokes fn whenever it changes. Call
// the returned stop function to stop polling.
var OnResize = internal.OnResize

// RenderRow serializes cells back into a single line, emitting an SGR
// sequence only where the active style changes and a reset at the end.
var RenderRow = internal.RenderRow

// RestoreCursorPosition restores the cursor position to the last saved
// position using SaveCursorPosition. If no position was saved, it does nothing.
var RestoreCursorPosition = internal.RestoreCursorPosition

// RestoreTerminalState restores the terminal state to the given state.
var RestoreTerminalState = internal.RestoreTerminalState

var Row = internal.Row

// RuneWidth returns the number of terminal columns r occupies: 0 for
// combining marks and joiners that attach to the previous cell, 2 for wide
// East Asian characters, 1 otherwise.
var RuneWidth = internal.RuneWidth

// SaveCursorPosition saves the current cursor position, which can be restored
// later with RestoreCursorPosition.
var SaveCursorPosition = internal.SaveCursorPosition

// ScrollDown scrolls the terminal content down by n lines, moving the cursor up
// by n lines. If n is zero, it does nothing. New lines are added at the top of
// the screen.
var ScrollDown = internal.ScrollDown

// ScrollUp scrolls the terminal content up by n lines, moving the cursor down
// by n lines. If n is zero, it does nothing. New lines are added at the bottom
// of the screen.
var ScrollUp = internal.ScrollUp

// SetColorLevel sets the color mode for the terminal. It can be used to force
// a specific color mode (None, Basic, 256, TrueColor) regardless of the
// terminal's capabilities or environment variables. This can be useful for
// testing or when the terminal detection is incorrect.
var SetColorLevel = internal.SetColorLevel

// SetStdin sets the file to use for stdin. It is used by the package to read
// input events (keyboard, mouse, cursor position) and check terminal state.
var SetStdin = internal.SetStdin

// SetStdout sets the file to use for stdout. It is used by the package to write
// terminal control sequences and messages and to check terminal size.
var SetStdout = internal.SetStdout

// SetWindowTitle sets the terminal window title to the given string. It may
// not work on all terminals.
var SetWindowTitle = internal.SetWindowTitle

// ShowCursor shows the cursor, making it visible. It does not move the cursor
// or change its position. Call HideCursor to make the cursor invisible again.
var ShowCursor = internal.ShowCursor

// Spacer returns an empty item that grows to fill the available space along
// the container's main axis, pushing the surrounding items apart.
var Spacer = internal.Spacer

// StringWidth returns the number of terminal columns s occupies, ignoring
// SGR escape sequences.
var StringWidth = internal.StringWidth

// SupportsColor reports whether the terminal supports any color output. It
// returns true if the color mode is Basic, 256, or TrueColor, and false if it
// is None. This can be used to conditionally enable or disable color output in
// applications. Use SetColorLevel to force a specific color mode if needed.
var SupportsColor = internal.SupportsColor

// SupportsColorMode reports whether the terminal supports the specified color
// mode. It returns true if the current color mode is equal to or greater than
// the requested mode, and false otherwise. This can be used to check for
// specific color capabilities before using advanced color features.
var SupportsColorMode = internal.SupportsColorMode

// WithinRawMode runs the given function while stdin is in raw mode. If stdin is
// not already in raw mode, it will enter raw mode before running the function and
// restore the terminal state afterwards.
//
// Just like EnterRawMode, do not read from stdin while in raw mode, as it will
// interfere with the package's event reading. Use event callbacks instead.
var WithinRawMode = internal.WithinRawMode
